# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: mydb_development
  pool: 5
#  username: postgres
#  password: M24lubOpnr90
  username: someuser1
  password: somepassword
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mydb_test
  pool: 5
#  username: postgres
#  password: M24lubOpnr90
  username: someuser1
  password: somepassword
  host: localhost

production:
  adapter: postgresql
#  encoding: unicode
 # database: mydb_production
 # pool: 5
#  username: postgres
#  password: M24lubOpnr90
 # username: someuser1
#  password: somepassword
  #host: localhost

